{
 "title": "Availcheck",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(availcheck_errors, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Response time",
   "type": "graph",
   "description": "Response time (in ms)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "availcheck_response_time_ms{instance=\"$instance\"}",
     "legendFormat": "{{website}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "availcheck_errors{instance=\"$instance\"}",
     "legendFormat": "{{website}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "availcheck_timeouts{instance=\"$instance\"}",
     "legendFormat": "{{website}}"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "availcheck_response_size{instance=\"$instance\"}",
     "legendFormat": "{{website}}"
    }
   ]
  }
 ]
}